### ISSUE TITLE
Error importing package into Munki 2.2.4.2438 using munkiimport

### ISSUE THREAD

**Issue by cashxx** [rtrouton/Payload-Free-Package-Creator#3]
These packages that are created with Payload-Free-Package-Creator should be able to be imported into Munki right?  This may tie into this now that I am finding it.   https://groups.google.com/forum/#!topic/munki-dev/zPNfOTJVwlQ

WARNING: No valid Distribution or PackageInfo found.
Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 1148, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 1125, in main
    if not has_valid_install_critieria(catinfo):
  File "/usr/local/munki/makepkginfo", line 396, in has_valid_install_critieria
    or catinfo['installer_type'] == 'profile'
KeyError: 'installer_type'
Getting package info failed.

**Comment by rtrouton** [comment]
Payload-free packages generated with this tool should not be used with Munki. This is because it uses pkgbuild’s method of generating payload-free packages, which does not leave a recipt behind.

For more information on pkgbuild and it not leaving receipts behind, please see here:
http://www.openradar.me/radar?id=2583401

**Comment by rtrouton** [comment]
This issue should now be resolved by the latest release of Payload-Free Package Creator.app, which is using a different way of generating installer packages. For details on the change, please see here:

https://derflounder.wordpress.com/2015/05/21/payload-free-package-creator-app-revisited/
